# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hVh5bR6r4DDR/j5qZkKtmiLuEk4RLaTwfhQwDBPqd9y+qxbZHA48wKN35s34eiZgcpIrDlJkIrN/fLmWwPXI3PR2hbExn3uAcyYvMHbakuKObF4Oxx2T/1KLEm8no0ZKgJg+/xrDBGNbJwcHejklHXKpF0uNA3FrmmHNI3eWL8/hp/xUib36yRoB21PpF01htSYiUX/BVFO8k8JVfKACPCSXm+K3X+vunqeG+oT06hyqEKBYRx5ZLfbc4grHrWs8iwVmRJky+tDyTSH33Y/r3yitcl/ZmIQpKoO4iuY7FOXLSSa9SpfepxYuNaCdfjvSN7+wSyUQtdBrw93tBfPw0osstSMvJgomBSBT9SHUcdeuukL7CYcqXW4+LDw4FrAVhKydn9s8mt7l3cnMAqkHSRFxy+XYMjllrD9+gRgFUB21eB51O62VgpwX1CcMIt9lxdPupR85oyJMerkO1bvEhuruKAde1e5zms6M8iU8AzAEFGY7JVnOwsihEopJh/Yf+thC2tPVG2AbaH6R/sxuXowucSsSmcfKWFpO33/e6vfafrTf435N83SKhQ2RYDbKM/qXgIXO5hw1LLW5fmQlKUWuPGxuPpVK9YHOR33gjaKqnCWqQ1DBVUapfSROFvt8q1nNOKV/nPAiaS+nyGbEFC+pN/1CRh5R8csgKG0nhOg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
