travis:
  secure:
    BINSTAR_TOKEN: SIrfKgNsQii1PLNP0Lgsm2aaGiW+BxefaV8BvuwBUbyFOvCl20hp9MQSU8K/5Ekdrmn2+MzP4wQ5qqfJBNnCGKY8UsTUkVOYGFrNN6pthpOiDzXYexvHw5s0aFdIjLuOB752+92HaiBhJO0VsT2BBCcvRI2KTPhEaOWhB3FvQz27PqHSRfBrM+Q0CGxfs9HJaeYKxVuCfJzTMGaK0b6ewoXJHot1xcYcJ1H4eLBywKcaHcZ9nnKdDvDLRmdbrqhFTsVkAfdo7N20zdELMpu4wOGZ29+XJEj/HdYWGoOCmdtH2imOYy97QANyFxsrJJBCyh532gSqKCMvJgQbLZFKPszHDB/l/Wk5ClAr9bPSqiqtbRgD0T6Pda7PfF+Ri9yPQcMGrnMv9at9mvOClA9JpgDQ32ZKBypcTC/vLRu+Vgsfp6t1YYo1uhtK6Ya+QJ4eakW2GqE82XfB44jme1OqWLLeKoKpT03pea3JMiFBImUfpGCQn3WD5MTxC43lGRfO5sTe7Hpt+Bt+PakJy9+Bfh977pZDevihEQVhB6e0A2TfPF9YIwSi+EbpbiacJqD6Xyy/DMxvKAYSQH5ijNYSedi4iyC0GvsJBjmmTS2uT5U8mBjLarsaVtmay5CwChFvq/czIpUlyER6AxZtD7KOTj3eOqOdvaGxWqL/flqNBy8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
