travis:
  secure:
    BINSTAR_TOKEN: hVh5bR6r4DDR/j5qZkKtmiLuEk4RLaTwfhQwDBPqd9y+qxbZHA48wKN35s34eiZgcpIrDlJkIrN/fLmWwPXI3PR2hbExn3uAcyYvMHbakuKObF4Oxx2T/1KLEm8no0ZKgJg+/xrDBGNbJwcHejklHXKpF0uNA3FrmmHNI3eWL8/hp/xUib36yRoB21PpF01htSYiUX/BVFO8k8JVfKACPCSXm+K3X+vunqeG+oT06hyqEKBYRx5ZLfbc4grHrWs8iwVmRJky+tDyTSH33Y/r3yitcl/ZmIQpKoO4iuY7FOXLSSa9SpfepxYuNaCdfjvSN7+wSyUQtdBrw93tBfPw0osstSMvJgomBSBT9SHUcdeuukL7CYcqXW4+LDw4FrAVhKydn9s8mt7l3cnMAqkHSRFxy+XYMjllrD9+gRgFUB21eB51O62VgpwX1CcMIt9lxdPupR85oyJMerkO1bvEhuruKAde1e5zms6M8iU8AzAEFGY7JVnOwsihEopJh/Yf+thC2tPVG2AbaH6R/sxuXowucSsSmcfKWFpO33/e6vfafrTf435N83SKhQ2RYDbKM/qXgIXO5hw1LLW5fmQlKUWuPGxuPpVK9YHOR33gjaKqnCWqQ1DBVUapfSROFvt8q1nNOKV/nPAiaS+nyGbEFC+pN/1CRh5R8csgKG0nhOg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
